version: '3.8'

networks:
  okr_network:
    name: "okr_network_${OKR_APP_DEPLOY_MODE:-staging}"
    driver: bridge

services:
  backend:
    container_name: "okr_backend_${OKR_APP_DEPLOY_MODE:-staging}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/okr_db
    networks:
      - okr_network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "okr_db_${OKR_APP_DEPLOY_MODE:-staging}"
    image: postgres:latest
    environment:
      # POSTGRES environment variables
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: okr_db
    ports:
      - "${DB_HOST_PORT:-5433}:5432"
    volumes:
      # Raw data file storage
      - postgres_data:/var/lib/postgresql/data

      # Hook to Postgres initialization process
      # Mount Prod or Staging initialization sql script
      # the file name can be arbitrary: ie init.sql, init_db.sql, db.sql, etc
      - "./db/init_${OKR_APP_DEPLOY_MODE:-staging}.sql:/docker-entrypoint-initdb.d/init_db.sql"

      # Mount SQL Script to initialize DB Schema (tables), imported in init_db.sql
      - "./db/schema.sql:/db/schema.sql"

      # Mount SQL Script to add toy data into tables, imported in init_db.sql, if empty DB and on Staging deployment
      - "./db/data.sql:/db/data.sql"
    networks:
      - okr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: "okr_frontend_${OKR_APP_DEPLOY_MODE:-staging}"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - OKR_BACKEND_URL=http://okr_backend_${OKR_APP_DEPLOY_MODE}:8000
    working_dir: /app
    volumes:
      - ./frontend/app.py:/app/app.py
      - ./frontend/key_results_card.py:/app/key_results_card.py
      - ./frontend/key_result_item.py:/app/key_result_item.py
      - ./frontend/key_result_item_edit.py:/app/key_result_item_edit.py
      - ./frontend/key_result_item_view.py:/app/key_result_item_view.py
      - ./frontend/key_result_item_v2.py:/app/key_result_item_v2.py
      - ./frontend/key_result_to_add_to_objective.py:/app/key_result_to_add_to_objective.py
      - ./frontend/key_result_item_creation_ui.py:/app/key_result_item_creation_ui.py

      - ./frontend/knowledge_base.py:/app/knowledge_base.py

    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - okr_network


  # One-off database Migration command
  alembic:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: alembic
    volumes:
      # Configure Alembic with correct sqlalchemy.url
      - ./backend/alembic.ini:/app/alembic.ini
      # Add migrations timeline/dependency chain
      - ./backend/migrations:/app/migrations
    networks:
      - okr_network
    depends_on:
      db:
        condition: service_healthy
    entrypoint: "alembic"

    # EG: Gen migration .py and run SQL: alembic revision --autogenerate -m "<commit message>"
    #     docker-compose run -it --build --rm alembic revision --autogenerate -m "<commit-like message>"
    
    # EG: Gen migration .py and print SQL in console: alembic revision --sql -m "<commit message>"
    #     docker-compose run -it --build --rm alembic revision --sql -m "<commit message>"


  # One-off Test Database Schema command
  # docker-compose run -it --build --rm test_db_schema
  test_db_schema:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    volumes:
      # mount test folder to make Tests available inside container
      - ./backend/tests:/app/tests
    networks:
      - okr_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@okr_db_${OKR_APP_DEPLOY_MODE:-staging}:5432/okr_db
    entrypoint: "pytest"
    command: ["-ra", "-vvs", "-k", "test_schema"]


volumes:
  postgres_data:
    name: "postgres_data_${OKR_APP_DEPLOY_MODE:-staging}"
