"""add 'min_progress_value' and 'max_progress_value' columns in KeyResult

Revision ID: 0464ab164d58
Revises: 
Create Date: 2025-09-24 18:53:23.479606

"""
import typing as t

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0464ab164d58'
down_revision: t.Union[str, t.Sequence[str], None] = None
branch_labels: t.Union[str, t.Sequence[str], None] = None
depends_on: t.Union[str, t.Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_results', sa.Column('short_description', sa.String(length=255), nullable=True))
    op.add_column('key_results', sa.Column('min_progress_value', sa.Integer(), server_default='0', nullable=False, comment='Minimum value for progress tracking (>=0)'))
    op.add_column('key_results', sa.Column('max_progress_value', sa.Integer(), server_default='100', nullable=False, comment='Maximum value for progress tracking (>min_progress_value)'))
    op.alter_column('key_results', 'objective_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('key_results', 'progress',
               existing_type=sa.INTEGER(),
               comment='Current progress value between min_progress_value and max_progress_value',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('key_results', 'metric',
               existing_type=sa.VARCHAR(length=255),
               comment='Metric for measuring progress',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_results', 'metric',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Metric for measuring progress',
               existing_nullable=True)
    op.alter_column('key_results', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current progress value between min_progress_value and max_progress_value',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('key_results', 'objective_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('key_results', 'max_progress_value')
    op.drop_column('key_results', 'min_progress_value')
    op.drop_column('key_results', 'short_description')
    # ### end Alembic commands ###
